const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],RM=matchMedia('(prefers-reduced-motion:reduce)').matches,LOW=RM||(navigator.hardwareConcurrency||8)<=4||innerWidth<700;
const NAV=['HOME','ABOUT','SERVICES','SOLUTIONS','INDUSTRIES','PROJECTS','INSIGHTS','CONTACT'],ID=['home','about','services','solutions','industries','projects','insights','contact'];
NAV.forEach((n,i)=>{const h=`<a href="#${ID[i]}" data-c="GO">${n}</a>`;$('#lk').insertAdjacentHTML('beforeend',h);$('#menu').insertAdjacentHTML('beforeend',h);$('#fn').insertAdjacentHTML('beforeend',`<a href="#${ID[i]}">${n[0]+n.slice(1).toLowerCase()}</a>`)});
$('#bg').onclick=()=>{const o=$('#menu').classList.toggle('o');$('#bg').setAttribute('aria-expanded',o);$('#bg').textContent=o?'CLOSE':'MENU';$('#menu').setAttribute('aria-hidden',!o)};$$('#menu a').forEach(a=>a.onclick=()=>$('#bg').click());
/* loader */
let p=0;const ld=setInterval(()=>{p=Math.min(100,p+(RM?50:7));const f=Math.round(p/6.25);$('#bar').textContent='['+'█'.repeat(f)+'░'.repeat(16-f)+'] '+p+'%';if(p>=100){clearInterval(ld);setTimeout(()=>$('#load').classList.add('off'),250)}},60);
/* scroll */
addEventListener('scroll',()=>{const y=scrollY,h=document.documentElement.scrollHeight-innerHeight;$('#prog').style.width=y/h*100+'%';$('#nav').classList.toggle('s',y>40);rs();pr()},{passive:true});
const io=new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.2});$$('.rv').forEach(e=>io.observe(e));
new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting)$$('.links a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+x.target.id))}),{threshold:.4}).observe&&$$('section').forEach(s=>new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting)$$('.links a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+x.target.id))}),{threshold:.35}).observe(s));
/* counters (placeholder scramble) */
$$('[data-s]').forEach(el=>new IntersectionObserver(([e],o)=>{if(!e.isIntersecting)return;o.disconnect();let t=0;const i=setInterval(()=>{el.textContent=t++<18?String(Math.random()*99|0).padStart(2,'0'):(clearInterval(i),'XX')},60)}).observe(el));
/* cursor + magnetic */
const cu=$('#cur');addEventListener('pointermove',e=>{cu.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;const t=e.target.closest('[data-c],button,a,.sv');cu.classList.toggle('x',!!t);cu.textContent=t?(t.dataset.c||'VIEW'):''});
$$('.mag').forEach(b=>{b.onpointermove=e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.2}px,${(e.clientY-r.top-r.height/2)*.3}px)`};b.onpointerleave=()=>b.style.transform=''});
/* services */
const SERVICES=[['GIS & Spatial Analysis','Spatial modelling and analysis of location-based data.',['QGIS','ArcGIS','Overlay']],['Remote Sensing','Interpreting satellite and aerial imagery for land, water and vegetation.',['Multispectral','Classification']],['Geospatial Data Management','Structuring and maintaining spatial databases.',['PostGIS','Metadata']],['Digital Mapping','Cartography and thematic maps for decision-makers.',['Cartography','Layers']],['WebGIS Development','Interactive web maps and geospatial portals.',['MapLibre','APIs']],['Spatial Analytics','Turning spatial patterns into measurable insight.',['Hotspots','Change']],['3D Geospatial Visualization','Terrain and city models you can explore.',['Terrain','3D']],['Surveying & Mapping','Field-collected measurements and base maps.',['GNSS','Topographic']],['Earth Observation','Monitoring places and change through satellite time series.',['Time series','Monitoring']],['Custom Geospatial Solutions','Tailored workflows built around your problem.',['Automation','Python']]];
SERVICES.forEach((s,i)=>{const b=document.createElement('button');b.className='sv'+(i?'':' on');b.style.setProperty('--h',150+i*22);b.setAttribute('aria-expanded',!i);b.dataset.c='OPEN';
b.innerHTML=`<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="45"/><circle cx="50" cy="50" r="30"/><circle cx="50" cy="50" r="15"/><path d="M0 50h100M50 0v100"/></svg><span class="m">${String(i+1).padStart(2,'0')} · ${(28+i*.37).toFixed(2)}° N ${(77+i*.41).toFixed(2)}° E</span><div><h3>${s[0]}</h3><div class="d"><p>${s[1]} <span class="m">[TO CONFIRM]</span></p>${s[2].map(t=>`<em>${t}</em>`).join('')}</div></div>`;
b.onclick=()=>$$('.sv').forEach(x=>{x.classList.toggle('on',x===b);x.setAttribute('aria-expanded',x===b)});$('#svc').append(b)});
/* procedural terrain field */
const F=(x,y)=>(Math.sin(x*.09+Math.sin(y*.07)*2)+Math.sin(y*.11+Math.cos(x*.05)*2)+Math.sin((x+y)*.2)*.5+Math.sin(x*.31)*Math.sin(y*.27)*.3)/2.6;
function paint(c,fn){const x=c.getContext('2d'),W=c.width,H=c.height,d=x.createImageData(W,H);for(let j=0;j<H;j++)for(let i=0;i<W;i++){const k=(j*W+i)*4,r=fn(i,j,F(i,j),F(i*1.9+40,j*1.9+9));d.data.set([r[0],r[1],r[2],255],k)}x.putImageData(d,0,0)}
const sat=(i,j,h,g)=>h<-.22?[12,40,70+h*60]:h>.5?[150,140,120]:g>.35?[86,92,90]:[20+g*40,70+h*80,35+g*20];
/* map demo */
function initMap(){const L=[['SATELLITE',sat],['TERRAIN',(i,j,h)=>{const v=Math.abs(((h*14)%1+1)%1-.5)<.05;return v?[61,255,176]:[8+h*20,20+h*30,24+h*20]}],['STREETS',(i,j,h,g)=>{const gx=i%20<1.6||j%16<1.6;return h<-.25?[10,40,70]:gx?[70,80,86]:[13,18,22]}],['ANALYTICS',(i,j,h,g)=>{const v=(g+1)/2;return[10+v*60,30+v*225,60+v*140]}]],w=$('#map');
L.forEach((l,n)=>{const c=document.createElement('canvas');c.width=200;c.height=112;c.className='L'+(n?'':' on');paint(c,l[1]);w.prepend(c);const b=document.createElement('button');b.textContent=l[0];b.className=n?'':'on';b.onclick=()=>{$$('#map .L').forEach((x,k)=>x.classList.toggle('on',k==L.length-1-n));$$('#lt button').forEach(x=>x.classList.toggle('on',x===b))};$('#lt').append(b)});
$$('#map .L').reverse();$$('#map .L').forEach((c,k)=>c.classList.toggle('on',k==L.length-1));
$('#roads').innerHTML='<path d="M0 40C20 30 30 44 50 28S80 20 100 10"/><path d="M10 56C25 38 45 40 60 20L70 0"/><path d="M0 15L40 30 100 46"/>';[[30,52],[62,34],[80,60]].forEach(p=>w.insertAdjacentHTML('beforeend',`<i class="pin" style="left:${p[0]}%;top:${p[1]}%"></i>`));
let z=1;const sz=d=>{z=Math.max(1,Math.min(3,z+d));$$('#map .L,#roads').forEach(c=>c.style.transform=`scale(${z})`)};$('#zi').onclick=()=>sz(.5);$('#zo').onclick=()=>sz(-.5);
w.onpointermove=e=>{const r=w.getBoundingClientRect();$('#mr').textContent=`LAT ${(28.9-(e.clientY-r.top)/r.height*.6).toFixed(4)}° N  LON ${(77+(e.clientX-r.left)/r.width*.8).toFixed(4)}° E · demo`}}
initMap();
/* remote sensing */
const RS=[['Raw satellite image','Unprocessed scene: haze, uneven contrast.'],['Image processing','Corrected and enhanced for analysis.'],['Classification','Water, vegetation, urban and bare land separated.'],['Spatial analysis','Classes measured across a grid of analysis units.'],['Actionable insight','Change detection highlights where land has shifted.']];
paint($('#c0'),sat);paint($('#c1'),(i,j,h,g)=>h<-.22?[40,120,230]:g>.35?[160,168,178]:h>.5?[190,160,105]:[63,190,106]);paint($('#c2'),(i,j,h,g)=>F(i*.7+90,j*.7)>.42?[255,70,70]:[0,0,0]);
RS.forEach(()=>$('#st').insertAdjacentHTML('beforeend','<i></i>'));
function rs(){const e=$('#rs'),r=e.getBoundingClientRect(),t=Math.max(0,Math.min(.999,-r.top/(r.height-innerHeight))),k=Math.floor(t*5);$$('#st i').forEach((x,i)=>x.classList.toggle('on',i<=k));$('#rt').textContent=RS[k][0];$('#rd').textContent=RS[k][1];
$('#c0').style.filter=k==0?'blur(1.2px) brightness(1.3) saturate(.5)':k==1?'contrast(1.25) saturate(1.3)':'contrast(1.1)';$('#c1').style.opacity=k>=2?(k==4?.7:.95):0;$('#gr').style.opacity=k>=3?1:0;$('#c2').style.opacity=k>=4?.6:0;$('#c2').style.mixBlendMode='screen'}
/* industries */
const IND=[['Urban Planning',['Land-use mapping','Growth monitoring','Site suitability']],['Infrastructure',['Corridor mapping','Asset inventory','Terrain analysis']],['Agriculture',['Crop monitoring','Vegetation analysis','Land-use mapping','Water-resource assessment']],['Environment',['Habitat mapping','Land-cover change','Monitoring']],['Water Resources',['Watershed delineation','Surface-water mapping']],['Mining & Geology',['Terrain modelling','Site mapping']],['Disaster Management',['Hazard mapping','Damage assessment']],['Transportation',['Network analysis','Route planning']],['Energy',['Site selection','Corridor analysis']],['Government & Public Sector',['Spatial data platforms','Planning support']]];
IND.forEach((d,i)=>{const b=document.createElement('button');b.textContent=d[0];b.dataset.c='VIEW';b.onclick=()=>{$$('#il button').forEach(x=>x.classList.toggle('on',x===b));$('#ip').innerHTML=`<svg viewBox="0 0 100 60" preserveAspectRatio="none" fill="none" stroke="hsl(${150+i*20},80%,60%)" stroke-width=".25">${[...Array(9)].map((_,n)=>`<path d="M0 ${8+n*6}C25 ${n*4} 45 ${20+n*5} 100 ${5+n*6}"/>`).join('')}</svg><span class="m">Illustrative · confirm sector</span><h3 style="font-size:clamp(28px,4vw,52px);margin:6px 0;letter-spacing:-.03em">${d[0]}</h3><ul>${d[1].map(a=>`<li>${a}</li>`).join('')}</ul>`};$('#il').append(b)});$('#il button').click();
/* process */
[['DISCOVER','Understand the geographic problem.'],['CAPTURE','Acquire satellite, survey or spatial data.'],['PROCESS','Clean, transform and structure the data.'],['ANALYZE','Apply GIS, remote sensing and spatial analytics.'],['VISUALIZE','Turn complex datasets into understandable maps and interfaces.'],['DECIDE','Deliver insights that support real-world decisions.']].forEach((s,i)=>$('#pr').insertAdjacentHTML('beforeend',`<div class="ps"><span class="m">Step ${i+1} of 6</span><h3>${s[0]}</h3><p>${s[1]}</p></div>`));
function pr(){const b=$('#pr').getBoundingClientRect(),y=innerHeight*.6-b.top;$('#pl').style.height=Math.max(0,Math.min(b.height,y))+'px';$$('.ps').forEach(s=>s.classList.toggle('on',s.offsetTop<y))}
['GIS','Remote Sensing','Satellite Imagery','Spatial Databases','WebGIS','3D Visualization','Python','PostGIS','QGIS','ArcGIS','GDAL','GeoServer','MapLibre','Three.js'].forEach(t=>$('#tg').insertAdjacentHTML('beforeend',`<span>${t}</span>`));
[['URBAN MAPPING'],['REMOTE SENSING ANALYSIS'],['SPATIAL DATA PLATFORM'],['ENVIRONMENTAL MONITORING']].forEach((c,i)=>$('#cs').insertAdjacentHTML('beforeend',`<a href="#contact" style="--h:${170+i*35}" data-c="VIEW"><span class="m">Project 0${i+1} · Case study placeholder</span><h3>${c[0]}</h3><p style="color:var(--mu);margin:4px 0 0">[Client, location, scope and results to be added once verified.]</p></a>`));
/* dashboard */
(()=>{const d=[...Array(30)].map((_,i)=>50-Math.sin(i*.4)*22-Math.sin(i*1.3)*8-i*.6);$('#ch').innerHTML=`<path d="M0 100 ${d.map((y,i)=>`L${i*10.3} ${y}`).join(' ')} L300 100Z" fill="rgba(56,182,255,.12)"/><path d="M${d.map((y,i)=>`${i*10.3} ${y}`).join(' L')}" fill="none" stroke="#38b6ff" stroke-width="1.2" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1"><animate attributeName="stroke-dashoffset" from="1" to="0" dur="2.5s" fill="freeze"/></path>`;
$('#bars').innerHTML=[70,45,88,30,60].map((v,i)=>`<rect x="${i*40+6}" y="${100-v}" width="26" height="${v}" fill="#3dffb0" opacity="${.35+i*.13}"><animate attributeName="height" from="0" to="${v}" dur="1.2s" begin="${i*.15}s" fill="freeze"/><animate attributeName="y" from="100" to="${100-v}" dur="1.2s" begin="${i*.15}s" fill="freeze"/></rect>`).join('')})();
$('#fm').onsubmit=e=>{e.preventDefault();$('#fs').textContent='Form is a front-end demo — connect it to your email or CRM endpoint.'};
/* Three.js: globe + terrain */
function gl(){if(!window.THREE)return;const cv=$('#gl'),R=new THREE.WebGLRenderer({canvas:cv,antialias:!LOW,alpha:!0});R.setPixelRatio(Math.min(devicePixelRatio,LOW?1:2));const S=new THREE.Scene(),C=new THREE.PerspectiveCamera(40,1,.1,50);C.position.z=4;
const G=new THREE.Group();S.add(G);const v=(la,lo,r=1)=>{la*=Math.PI/180;lo*=Math.PI/180;return new THREE.Vector3(r*Math.cos(la)*Math.sin(lo),r*Math.sin(la),r*Math.cos(la)*Math.cos(lo))};
const N=LOW?3500:9000,pos=[];for(let i=0;i<N*3;i++){const la=Math.asin(1-2*Math.random())*57.3,lo=Math.random()*360;if(F(lo*.9,la*1.4+30)>-.05){const q=v(la,lo);pos.push(q.x,q.y,q.z)}}
const pg=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(pos,3));G.add(new THREE.Points(pg,new THREE.PointsMaterial({color:0x5fd9c0,size:.012,transparent:!0,opacity:.75})));
G.add(new THREE.Mesh(new THREE.SphereGeometry(.985,48,48),new THREE.MeshBasicMaterial({color:0x061014})));G.add(new THREE.LineSegments(new THREE.WireframeGeometry(new THREE.SphereGeometry(1.002,18,12)),new THREE.LineBasicMaterial({color:0x3dffb0,transparent:!0,opacity:.07})));
const pts=[[28.6,77.2],[51.5,0],[35.7,139.7],[-33.9,151.2],[40.7,-74],[-23.5,-46.6],[-1.3,36.8]],mk=new THREE.Mesh(new THREE.SphereGeometry(.02,8,8),new THREE.MeshBasicMaterial({color:0x3dffb0}));pts.forEach(p=>{const m=mk.clone();m.position.copy(v(p[0],p[1],1.01));G.add(m)});
for(let i=1;i<pts.length;i+=1){const a=v(...pts[0]),b=v(...pts[i]),c=a.clone().add(b).multiplyScalar(.5).normalize().multiplyScalar(1.6);G.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(new THREE.QuadraticBezierCurve3(a,c,b).getPoints(40)),new THREE.LineBasicMaterial({color:0x38b6ff,transparent:!0,opacity:.45})))}
const at=new THREE.Mesh(new THREE.SphereGeometry(1.2,48,48),new THREE.ShaderMaterial({transparent:!0,side:THREE.BackSide,blending:THREE.AdditiveBlending,vertexShader:'varying vec3 n;void main(){n=normalize(normalMatrix*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 n;void main(){float i=pow(.72-dot(n,vec3(0,0,1.)),3.);gl_FragColor=vec4(.2,.9,.8,1.)*i;}'}));S.add(at);
const orb=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(1.5,.003,4,120),new THREE.MeshBasicMaterial({color:0x38b6ff,transparent:!0,opacity:.6})),sa=new THREE.Mesh(new THREE.BoxGeometry(.04,.02,.02),new THREE.MeshBasicMaterial({color:0xffffff}));orb.add(ring,sa);orb.rotation.set(1.2,.3,0);S.add(orb);
let mx=0,my=0,t=0;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5});
function fit(){const w=cv.clientWidth,h=cv.clientHeight;R.setSize(w,h,!1);C.aspect=w/h;C.updateProjectionMatrix();const m=w<900;G.position.set(m?0:1.1,m?.6:0,0);at.position.copy(G.position);orb.position.copy(G.position);G.scale.setScalar(m?.85:1);at.scale.setScalar(m?.85:1);orb.scale.setScalar(m?.85:1)}fit();addEventListener('resize',fit);
let vis=!0;new IntersectionObserver(([e])=>vis=e.isIntersecting).observe(cv);
(function loop(){if(vis){t+=.004;G.rotation.y=t+mx*.5;G.rotation.x=my*.3;sa.position.set(Math.cos(t*4)*1.5,Math.sin(t*4)*1.5,0);R.render(S,C);$('#co').textContent=`${(28.6139+Math.sin(t)*.02).toFixed(4)}° N ${(77.209+Math.cos(t)*.02).toFixed(4)}° E`}if(!RM)requestAnimationFrame(loop)})();if(RM)R.render(S,C)}
function terr(){if(!window.THREE)return;const cv=$('#tc'),R=new THREE.WebGLRenderer({canvas:cv,alpha:!0}),S=new THREE.Scene(),C=new THREE.PerspectiveCamera(45,1,.1,100),n=LOW?40:70;R.setPixelRatio(1);C.position.set(0,5,8);C.lookAt(0,0,0);
const g=new THREE.PlaneGeometry(14,10,n,n);g.rotateX(-Math.PI/2);const p=g.attributes.position,base=[];for(let i=0;i<p.count;i++){const h=F(p.getX(i)*7,p.getZ(i)*7)*1.4;base.push(h);p.setY(i,h)}
const m=new THREE.Points(g,new THREE.PointsMaterial({color:0x3dffb0,size:.035,transparent:!0,opacity:.8}));S.add(m);const bm=new THREE.Mesh(new THREE.PlaneGeometry(14,.04),new THREE.MeshBasicMaterial({color:0x38b6ff,transparent:!0,opacity:.7}));bm.rotation.x=-Math.PI/2;bm.position.y=1.2;S.add(bm);
const fit=()=>{R.setSize(cv.clientWidth,cv.clientHeight,!1);C.aspect=cv.clientWidth/cv.clientHeight;C.updateProjectionMatrix()};fit();addEventListener('resize',fit);let vis=!1,t=0;new IntersectionObserver(([e])=>vis=e.isIntersecting).observe(cv);
(function l(){if(vis){t+=.01;m.rotation.y=Math.sin(t*.3)*.4;bm.position.z=Math.sin(t)*4.5;for(let i=0;i<p.count;i++)p.setY(i,base[i]+Math.sin(t+p.getX(i))*.05);p.needsUpdate=!0;R.render(S,C)}if(!RM)requestAnimationFrame(l)})();if(RM){vis=!0;R.render(S,C)}}
try{gl();terr()}catch(e){console.warn('WebGL unavailable — CSS fallback in use')}rs();pr();
